### ISSUE TITLE
Is there a possibility in that source code to make the detection "lower", to combine also panorama if not every neighbour pixel is detected?

### ISSUE THREAD

**Issue by installthetech** [installthetech/slit_scan_panorama#3]

**Comment by installthetech** [comment]
In case of detection on lower resolution on lesser features, Try tuning these parameters in PRIMEPANORAMA.cpp:

  MAXFEAT = 50;
  SCALEFACTOR = 1.2f;
  EDGETHRESH = 31;
  FIRSTLEVEL = 0;
  PATCHSIZE = 31;
  FASTTHRESH = 30;
  
Try lowering these values as per your requirements.

**Comment by zweipunktnull** [comment]
Hey Vinay! Thanks it helped me a lot!!
Now one more question, is there a possibility to make the panorama as long as the video time, that means that it is not get cropped before and end earlier.

Greetings 
Chris

**Comment by installthetech** [comment]
Hey hi, sorry for late reply.

Can you give some more details on the problem?

**Comment by installthetech** [comment]
Made a new issue[ here ](https://github.com/installthetech/slit_scan_panorama/issues/4)
